### ISSUE TITLE
Version 0.1

### ISSUE THREAD

**Issue by nuta** [resea/resea#8]
## Bug fixes
- [x] #6: Something wrong with vprintfmt() zero-padding

## Refactoring
- [x] #7: Reimplement build system
- [x] #16: Reimplement Base
- [x] #14: refine rt/c
- [x] #2: refine IDL 
- [x] #12: Replace start_builtin_servers()
